name: build deployment

on: 
  push: 
    branches: [main]
  workflow_dispatch:

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build React 
        run: | 
          yarn install
          yarn build
          echo ${{ secrets.KEY }} > private.key
          scp -i "private.key" -r build/* ${{ secrets.USER }}@${{ secrets.HOST }}:/var/www/bw/build
