name: build deployment

on: 
  push: 
    branches: [main]
  workflow_dispatch:

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build React 
        run: | 
          yarn install
          yarn build
      - name: copy build via ssh key
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USER }}
            key: ${{ secrets.KEY }}
            source: "build/*"
            target: "/var/www/bw/build"
